server:
  port: 32099
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudstorage
    username: cloudstorage
    password: CloudStorage:2871
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    com.silvericekey.cloudstorage: debug
